// for falgs --> https://history.state.gov/countries/all
// image border adder url --> https://www.tuxpi.com/photo-effects/borders

// All countries
// length 252
var countries = [
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Afghanistan", "code": "AF", "id": 1, "phone": 93, "symbol": "؋", "capital": "Kabul", "currency": "AFN", "continent": "Asia", "continent_code": "AS", "alpha_3": "AFG" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Aland Islands", "code": "AX", "id": 2, "phone": 358, "symbol": "€", "capital": "Mariehamn", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "ALA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Albania", "code": "AL", "id": 3, "phone": 355, "symbol": "Lek", "capital": "Tirana", "currency": "ALL", "continent": "Europe", "continent_code": "EU", "alpha_3": "ALB" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Algeria", "code": "DZ", "id": 4, "phone": 213, "symbol": "دج", "capital": "Algiers", "currency": "DZD", "continent": "Africa", "continent_code": "AF", "alpha_3": "DZA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "American Samoa", "code": "AS", "id": 5, "phone": 1684, "symbol": "$", "capital": "Pago Pago", "currency": "USD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "ASM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Andorra", "code": "AD", "id": 6, "phone": 376, "symbol": "€", "capital": "Andorra la Vella", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "AND" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Angola", "code": "AO", "id": 7, "phone": 244, "symbol": "Kz", "capital": "Luanda", "currency": "AOA", "continent": "Africa", "continent_code": "AF", "alpha_3": "AGO" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Anguilla", "code": "AI", "id": 8, "phone": 1264, "symbol": "$", "capital": "The Valley", "currency": "XCD", "continent": "North America", "continent_code": "NA", "alpha_3": "AIA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Antarctica", "code": "AQ", "id": 9, "phone": 672, "symbol": "$", "capital": "Antarctica", "currency": "AAD", "continent": "Antarctica", "continent_code": "AN", "alpha_3": "ATA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Antigua and Barbuda", "code": "AG", "id": 10, "phone": 1268, "symbol": "$", "capital": "St. John's", "currency": "XCD", "continent": "North America", "continent_code": "NA", "alpha_3": "ATG" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Argentina", "code": "AR", "id": 11, "phone": 54, "symbol": "$", "capital": "Buenos Aires", "currency": "ARS", "continent": "South America", "continent_code": "SA", "alpha_3": "ARG" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Armenia", "code": "AM", "id": 12, "phone": 374, "symbol": "֏", "capital": "Yerevan", "currency": "AMD", "continent": "Asia", "continent_code": "AS", "alpha_3": "ARM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Aruba", "code": "AW", "id": 13, "phone": 297, "symbol": "ƒ", "capital": "Oranjestad", "currency": "AWG", "continent": "North America", "continent_code": "NA", "alpha_3": "ABW" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Australia", "code": "AU", "id": 14, "phone": 61, "symbol": "$", "capital": "Canberra", "currency": "AUD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "AUS" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Austria", "code": "AT", "id": 15, "phone": 43, "symbol": "€", "capital": "Vienna", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "AUT" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Azerbaijan", "code": "AZ", "id": 16, "phone": 994, "symbol": "m", "capital": "Baku", "currency": "AZN", "continent": "Asia", "continent_code": "AS", "alpha_3": "AZE" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Bahamas", "code": "BS", "id": 17, "phone": 1242, "symbol": "B$", "capital": "Nassau", "currency": "BSD", "continent": "North America", "continent_code": "NA", "alpha_3": "BHS" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Bahrain", "code": "BH", "id": 18, "phone": 973, "symbol": ".د.ب", "capital": "Manama", "currency": "BHD", "continent": "Asia", "continent_code": "AS", "alpha_3": "BHR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Bangladesh", "code": "BD", "id": 19, "phone": 880, "symbol": "৳", "capital": "Dhaka", "currency": "BDT", "continent": "Asia", "continent_code": "AS", "alpha_3": "BGD" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Barbados", "code": "BB", "id": 20, "phone": 1246, "symbol": "Bds$", "capital": "Bridgetown", "currency": "BBD", "continent": "North America", "continent_code": "NA", "alpha_3": "BRB" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Belarus", "code": "BY", "id": 21, "phone": 375, "symbol": "Br", "capital": "Minsk", "currency": "BYN", "continent": "Europe", "continent_code": "EU", "alpha_3": "BLR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Belgium", "code": "BE", "id": 22, "phone": 32, "symbol": "€", "capital": "Brussels", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "BEL" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Belize", "code": "BZ", "id": 23, "phone": 501, "symbol": "$", "capital": "Belmopan", "currency": "BZD", "continent": "North America", "continent_code": "NA", "alpha_3": "BLZ" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Benin", "code": "BJ", "id": 24, "phone": 229, "symbol": "CFA", "capital": "Porto-Novo", "currency": "XOF", "continent": "Africa", "continent_code": "AF", "alpha_3": "BEN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Bermuda", "code": "BM", "id": 25, "phone": 1441, "symbol": "$", "capital": "Hamilton", "currency": "BMD", "continent": "North America", "continent_code": "NA", "alpha_3": "BMU" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Bhutan", "code": "BT", "id": 26, "phone": 975, "symbol": "Nu.", "capital": "Thimphu", "currency": "BTN", "continent": "Asia", "continent_code": "AS", "alpha_3": "BTN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Bolivia", "code": "BO", "id": 27, "phone": 591, "symbol": "Bs.", "capital": "Sucre", "currency": "BOB", "continent": "South America", "continent_code": "SA", "alpha_3": "BOL" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Bonaire, Sint Eustatius and Saba", "code": "BQ", "id": 28, "phone": 599, "symbol": "$", "capital": "Kralendijk", "currency": "USD", "continent": "North America", "continent_code": "NA", "alpha_3": "BES" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Bosnia and Herzegovina", "code": "BA", "id": 29, "phone": 387, "symbol": "KM", "capital": "Sarajevo", "currency": "BAM", "continent": "Europe", "continent_code": "EU", "alpha_3": "BIH" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Botswana", "code": "BW", "id": 30, "phone": 267, "symbol": "P", "capital": "Gaborone", "currency": "BWP", "continent": "Africa", "continent_code": "AF", "alpha_3": "BWA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Bouvet Island", "code": "BV", "id": 31, "phone": 55, "symbol": "kr", "capital": "", "currency": "NOK", "continent": "Antarctica", "continent_code": "AN", "alpha_3": "BVT" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Brazil", "code": "BR", "id": 32, "phone": 55, "symbol": "R$", "capital": "Brasilia", "currency": "BRL", "continent": "South America", "continent_code": "SA", "alpha_3": "BRA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "British Indian Ocean Territory", "code": "IO", "id": 33, "phone": 246, "symbol": "$", "capital": "Diego Garcia", "currency": "USD", "continent": "Asia", "continent_code": "AS", "alpha_3": "IOT" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Brunei Darussalam", "code": "BN", "id": 34, "phone": 673, "symbol": "B$", "capital": "Bandar Seri Begawan", "currency": "BND", "continent": "Asia", "continent_code": "AS", "alpha_3": "BRN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Bulgaria", "code": "BG", "id": 35, "phone": 359, "symbol": "Лв.", "capital": "Sofia", "currency": "BGN", "continent": "Europe", "continent_code": "EU", "alpha_3": "BGR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Burkina Faso", "code": "BF", "id": 36, "phone": 226, "symbol": "CFA", "capital": "Ouagadougou", "currency": "XOF", "continent": "Africa", "continent_code": "AF", "alpha_3": "BFA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Burundi", "code": "BI", "id": 37, "phone": 257, "symbol": "FBu", "capital": "Bujumbura", "currency": "BIF", "continent": "Africa", "continent_code": "AF", "alpha_3": "BDI" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Cambodia", "code": "KH", "id": 38, "phone": 855, "symbol": "KHR", "capital": "Phnom Penh", "currency": "KHR", "continent": "Asia", "continent_code": "AS", "alpha_3": "KHM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Cameroon", "code": "CM", "id": 39, "phone": 237, "symbol": "FCFA", "capital": "Yaounde", "currency": "XAF", "continent": "Africa", "continent_code": "AF", "alpha_3": "CMR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Canada", "code": "CA", "id": 40, "phone": 1, "symbol": "$", "capital": "Ottawa", "currency": "CAD", "continent": "North America", "continent_code": "NA", "alpha_3": "CAN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Cape Verde", "code": "CV", "id": 41, "phone": 238, "symbol": "$", "capital": "Praia", "currency": "CVE", "continent": "Africa", "continent_code": "AF", "alpha_3": "CPV" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Cayman Islands", "code": "KY", "id": 42, "phone": 1345, "symbol": "$", "capital": "George Town", "currency": "KYD", "continent": "North America", "continent_code": "NA", "alpha_3": "CYM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Central African Republic", "code": "CF", "id": 43, "phone": 236, "symbol": "FCFA", "capital": "Bangui", "currency": "XAF", "continent": "Africa", "continent_code": "AF", "alpha_3": "CAF" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Chad", "code": "TD", "id": 44, "phone": 235, "symbol": "FCFA", "capital": "N'Djamena", "currency": "XAF", "continent": "Africa", "continent_code": "AF", "alpha_3": "TCD" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Chile", "code": "CL", "id": 45, "phone": 56, "symbol": "$", "capital": "Santiago", "currency": "CLP", "continent": "South America", "continent_code": "SA", "alpha_3": "CHL" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "China", "code": "CN", "id": 46, "phone": 86, "symbol": "¥", "capital": "Beijing", "currency": "CNY", "continent": "Asia", "continent_code": "AS", "alpha_3": "CHN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Christmas Island", "code": "CX", "id": 47, "phone": 61, "symbol": "$", "capital": "Flying Fish Cove", "currency": "AUD", "continent": "Asia", "continent_code": "AS", "alpha_3": "CXR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Cocos (Keeling) Islands", "code": "CC", "id": 48, "phone": 672, "symbol": "$", "capital": "West Island", "currency": "AUD", "continent": "Asia", "continent_code": "AS", "alpha_3": "CCK" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Colombia", "code": "CO", "id": 49, "phone": 57, "symbol": "$", "capital": "Bogota", "currency": "COP", "continent": "South America", "continent_code": "SA", "alpha_3": "COL" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Comoros", "code": "KM", "id": 50, "phone": 269, "symbol": "CF", "capital": "Moroni", "currency": "KMF", "continent": "Africa", "continent_code": "AF", "alpha_3": "COM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Congo", "code": "CG", "id": 51, "phone": 242, "symbol": "FC", "capital": "Brazzaville", "currency": "XAF", "continent": "Africa", "continent_code": "AF", "alpha_3": "COG" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Congo, Democratic Republic of the Congo", "code": "CD", "id": 52, "phone": 242, "symbol": "FC", "capital": "Kinshasa", "currency": "CDF", "continent": "Africa", "continent_code": "AF", "alpha_3": "COD" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Cook Islands", "code": "CK", "id": 53, "phone": 682, "symbol": "$", "capital": "Avarua", "currency": "NZD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "COK" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Costa Rica", "code": "CR", "id": 54, "phone": 506, "symbol": "₡", "capital": "San Jose", "currency": "CRC", "continent": "North America", "continent_code": "NA", "alpha_3": "CRI" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Cote D'Ivoire", "code": "CI", "id": 55, "phone": 225, "symbol": "CFA", "capital": "Yamoussoukro", "currency": "XOF", "continent": "Africa", "continent_code": "AF", "alpha_3": "CIV" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Croatia", "code": "HR", "id": 56, "phone": 385, "symbol": "kn", "capital": "Zagreb", "currency": "HRK", "continent": "Europe", "continent_code": "EU", "alpha_3": "HRV" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Cuba", "code": "CU", "id": 57, "phone": 53, "symbol": "$", "capital": "Havana", "currency": "CUP", "continent": "North America", "continent_code": "NA", "alpha_3": "CUB" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Curacao", "code": "CW", "id": 58, "phone": 599, "symbol": "ƒ", "capital": "Willemstad", "currency": "ANG", "continent": "North America", "continent_code": "NA", "alpha_3": "CUW" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Cyprus", "code": "CY", "id": 59, "phone": 357, "symbol": "€", "capital": "Nicosia", "currency": "EUR", "continent": "Asia", "continent_code": "AS", "alpha_3": "CYP" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Czech Republic", "code": "CZ", "id": 60, "phone": 420, "symbol": "Kč", "capital": "Prague", "currency": "CZK", "continent": "Europe", "continent_code": "EU", "alpha_3": "CZE" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Denmark", "code": "DK", "id": 61, "phone": 45, "symbol": "Kr.", "capital": "Copenhagen", "currency": "DKK", "continent": "Europe", "continent_code": "EU", "alpha_3": "DNK" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Djibouti", "code": "DJ", "id": 62, "phone": 253, "symbol": "Fdj", "capital": "Djibouti", "currency": "DJF", "continent": "Africa", "continent_code": "AF", "alpha_3": "DJI" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Dominica", "code": "DM", "id": 63, "phone": 1767, "symbol": "$", "capital": "Roseau", "currency": "XCD", "continent": "North America", "continent_code": "NA", "alpha_3": "DMA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Dominican Republic", "code": "DO", "id": 64, "phone": 1809, "symbol": "$", "capital": "Santo Domingo", "currency": "DOP", "continent": "North America", "continent_code": "NA", "alpha_3": "DOM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Ecuador", "code": "EC", "id": 65, "phone": 593, "symbol": "$", "capital": "Quito", "currency": "USD", "continent": "South America", "continent_code": "SA", "alpha_3": "ECU" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Egypt", "code": "EG", "id": 66, "phone": 20, "symbol": "ج.م", "capital": "Cairo", "currency": "EGP", "continent": "Africa", "continent_code": "AF", "alpha_3": "EGY" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "El Salvador", "code": "SV", "id": 67, "phone": 503, "symbol": "$", "capital": "San Salvador", "currency": "USD", "continent": "North America", "continent_code": "NA", "alpha_3": "SLV" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Equatorial Guinea", "code": "GQ", "id": 68, "phone": 240, "symbol": "FCFA", "capital": "Malabo", "currency": "XAF", "continent": "Africa", "continent_code": "AF", "alpha_3": "GNQ" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Eritrea", "code": "ER", "id": 69, "phone": 291, "symbol": "Nfk", "capital": "Asmara", "currency": "ERN", "continent": "Africa", "continent_code": "AF", "alpha_3": "ERI" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Estonia", "code": "EE", "id": 70, "phone": 372, "symbol": "€", "capital": "Tallinn", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "EST" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Ethiopia", "code": "ET", "id": 71, "phone": 251, "symbol": "Nkf", "capital": "Addis Ababa", "currency": "ETB", "continent": "Africa", "continent_code": "AF", "alpha_3": "ETH" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Falkland Islands (Malvinas)", "code": "FK", "id": 72, "phone": 500, "symbol": "£", "capital": "Stanley", "currency": "FKP", "continent": "South America", "continent_code": "SA", "alpha_3": "FLK" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Faroe Islands", "code": "FO", "id": 73, "phone": 298, "symbol": "Kr.", "capital": "Torshavn", "currency": "DKK", "continent": "Europe", "continent_code": "EU", "alpha_3": "FRO" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Fiji", "code": "FJ", "id": 74, "phone": 679, "symbol": "FJ$", "capital": "Suva", "currency": "FJD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "FJI" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Finland", "code": "FI", "id": 75, "phone": 358, "symbol": "€", "capital": "Helsinki", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "FIN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "France", "code": "FR", "id": 76, "phone": 33, "symbol": "€", "capital": "Paris", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "FRA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "French Guiana", "code": "GF", "id": 77, "phone": 594, "symbol": "€", "capital": "Cayenne", "currency": "EUR", "continent": "South America", "continent_code": "SA", "alpha_3": "GUF" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "French Polynesia", "code": "PF", "id": 78, "phone": 689, "symbol": "₣", "capital": "Papeete", "currency": "XPF", "continent": "Oceania", "continent_code": "OC", "alpha_3": "PYF" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "French Southern Territories", "code": "TF", "id": 79, "phone": 262, "symbol": "€", "capital": "Port-aux-Francais", "currency": "EUR", "continent": "Antarctica", "continent_code": "AN", "alpha_3": "ATF" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Gabon", "code": "GA", "id": 80, "phone": 241, "symbol": "FCFA", "capital": "Libreville", "currency": "XAF", "continent": "Africa", "continent_code": "AF", "alpha_3": "GAB" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Gambia", "code": "GM", "id": 81, "phone": 220, "symbol": "D", "capital": "Banjul", "currency": "GMD", "continent": "Africa", "continent_code": "AF", "alpha_3": "GMB" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Georgia", "code": "GE", "id": 82, "phone": 995, "symbol": "ლ", "capital": "Tbilisi", "currency": "GEL", "continent": "Asia", "continent_code": "AS", "alpha_3": "GEO" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Germany", "code": "DE", "id": 83, "phone": 49, "symbol": "€", "capital": "Berlin", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "DEU" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Ghana", "code": "GH", "id": 84, "phone": 233, "symbol": "GH₵", "capital": "Accra", "currency": "GHS", "continent": "Africa", "continent_code": "AF", "alpha_3": "GHA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Gibraltar", "code": "GI", "id": 85, "phone": 350, "symbol": "£", "capital": "Gibraltar", "currency": "GIP", "continent": "Europe", "continent_code": "EU", "alpha_3": "GIB" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Greece", "code": "GR", "id": 86, "phone": 30, "symbol": "€", "capital": "Athens", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "GRC" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Greenland", "code": "GL", "id": 87, "phone": 299, "symbol": "Kr.", "capital": "Nuuk", "currency": "DKK", "continent": "North America", "continent_code": "NA", "alpha_3": "GRL" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Grenada", "code": "GD", "id": 88, "phone": 1473, "symbol": "$", "capital": "St. George's", "currency": "XCD", "continent": "North America", "continent_code": "NA", "alpha_3": "GRD" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Guadeloupe", "code": "GP", "id": 89, "phone": 590, "symbol": "€", "capital": "Basse-Terre", "currency": "EUR", "continent": "North America", "continent_code": "NA", "alpha_3": "GLP" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Guam", "code": "GU", "id": 90, "phone": 1671, "symbol": "$", "capital": "Hagatna", "currency": "USD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "GUM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Guatemala", "code": "GT", "id": 91, "phone": 502, "symbol": "Q", "capital": "Guatemala City", "currency": "GTQ", "continent": "North America", "continent_code": "NA", "alpha_3": "GTM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Guernsey", "code": "GG", "id": 92, "phone": 44, "symbol": "£", "capital": "St Peter Port", "currency": "GBP", "continent": "Europe", "continent_code": "EU", "alpha_3": "GGY" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Guinea", "code": "GN", "id": 93, "phone": 224, "symbol": "FG", "capital": "Conakry", "currency": "GNF", "continent": "Africa", "continent_code": "AF", "alpha_3": "GIN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Guinea-Bissau", "code": "GW", "id": 94, "phone": 245, "symbol": "CFA", "capital": "Bissau", "currency": "XOF", "continent": "Africa", "continent_code": "AF", "alpha_3": "GNB" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Guyana", "code": "GY", "id": 95, "phone": 592, "symbol": "$", "capital": "Georgetown", "currency": "GYD", "continent": "South America", "continent_code": "SA", "alpha_3": "GUY" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Haiti", "code": "HT", "id": 96, "phone": 509, "symbol": "G", "capital": "Port-au-Prince", "currency": "HTG", "continent": "North America", "continent_code": "NA", "alpha_3": "HTI" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Heard Island and Mcdonald Islands", "code": "HM", "id": 97, "phone": 0, "symbol": "$", "capital": "", "currency": "AUD", "continent": "Antarctica", "continent_code": "AN", "alpha_3": "HMD" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Holy See (Vatican City State)", "code": "VA", "id": 98, "phone": 39, "symbol": "€", "capital": "Vatican City", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "VAT" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Honduras", "code": "HN", "id": 99, "phone": 504, "symbol": "L", "capital": "Tegucigalpa", "currency": "HNL", "continent": "North America", "continent_code": "NA", "alpha_3": "HND" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Hong Kong", "code": "HK", "id": 100, "phone": 852, "symbol": "$", "capital": "Hong Kong", "currency": "HKD", "continent": "Asia", "continent_code": "AS", "alpha_3": "HKG" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Hungary", "code": "HU", "id": 101, "phone": 36, "symbol": "Ft", "capital": "Budapest", "currency": "HUF", "continent": "Europe", "continent_code": "EU", "alpha_3": "HUN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Iceland", "code": "IS", "id": 102, "phone": 354, "symbol": "kr", "capital": "Reykjavik", "currency": "ISK", "continent": "Europe", "continent_code": "EU", "alpha_3": "ISL" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "India", "code": "IN", "id": 103, "phone": 91, "symbol": "₹", "capital": "New Delhi", "currency": "INR", "continent": "Asia", "continent_code": "AS", "alpha_3": "IND" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Indonesia", "code": "ID", "id": 104, "phone": 62, "symbol": "Rp", "capital": "Jakarta", "currency": "IDR", "continent": "Asia", "continent_code": "AS", "alpha_3": "IDN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Iran, Islamic Republic of", "code": "IR", "id": 105, "phone": 98, "symbol": "﷼", "capital": "Tehran", "currency": "IRR", "continent": "Asia", "continent_code": "AS", "alpha_3": "IRN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Iraq", "code": "IQ", "id": 106, "phone": 964, "symbol": "د.ع", "capital": "Baghdad", "currency": "IQD", "continent": "Asia", "continent_code": "AS", "alpha_3": "IRQ" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Ireland", "code": "IE", "id": 107, "phone": 353, "symbol": "€", "capital": "Dublin", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "IRL" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Isle of Man", "code": "IM", "id": 108, "phone": 44, "symbol": "£", "capital": "Douglas, Isle of Man", "currency": "GBP", "continent": "Europe", "continent_code": "EU", "alpha_3": "IMN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Israel", "code": "IL", "id": 109, "phone": 972, "symbol": "₪", "capital": "Jerusalem", "currency": "ILS", "continent": "Asia", "continent_code": "AS", "alpha_3": "ISR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Italy", "code": "IT", "id": 110, "phone": 39, "symbol": "€", "capital": "Rome", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "ITA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Jamaica", "code": "JM", "id": 111, "phone": 1876, "symbol": "J$", "capital": "Kingston", "currency": "JMD", "continent": "North America", "continent_code": "NA", "alpha_3": "JAM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Japan", "code": "JP", "id": 112, "phone": 81, "symbol": "¥", "capital": "Tokyo", "currency": "JPY", "continent": "Asia", "continent_code": "AS", "alpha_3": "JPN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Jersey", "code": "JE", "id": 113, "phone": 44, "symbol": "£", "capital": "Saint Helier", "currency": "GBP", "continent": "Europe", "continent_code": "EU", "alpha_3": "JEY" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Jordan", "code": "JO", "id": 114, "phone": 962, "symbol": "ا.د", "capital": "Amman", "currency": "JOD", "continent": "Asia", "continent_code": "AS", "alpha_3": "JOR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Kazakhstan", "code": "KZ", "id": 115, "phone": 7, "symbol": "лв", "capital": "Astana", "currency": "KZT", "continent": "Asia", "continent_code": "AS", "alpha_3": "KAZ" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Kenya", "code": "KE", "id": 116, "phone": 254, "symbol": "KSh", "capital": "Nairobi", "currency": "KES", "continent": "Africa", "continent_code": "AF", "alpha_3": "KEN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Kiribati", "code": "KI", "id": 117, "phone": 686, "symbol": "$", "capital": "Tarawa", "currency": "AUD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "KIR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Korea, Democratic People's Republic of", "code": "KP", "id": 118, "phone": 850, "symbol": "₩", "capital": "Pyongyang", "currency": "KPW", "continent": "Asia", "continent_code": "AS", "alpha_3": "PRK" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Korea, Republic of", "code": "KR", "id": 119, "phone": 82, "symbol": "₩", "capital": "Seoul", "currency": "KRW", "continent": "Asia", "continent_code": "AS", "alpha_3": "KOR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Kosovo", "code": "XK", "id": 120, "phone": 381, "symbol": "€", "capital": "Pristina", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "XKX" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Kuwait", "code": "KW", "id": 121, "phone": 965, "symbol": "ك.د", "capital": "Kuwait City", "currency": "KWD", "continent": "Asia", "continent_code": "AS", "alpha_3": "KWT" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Kyrgyzstan", "code": "KG", "id": 122, "phone": 996, "symbol": "лв", "capital": "Bishkek", "currency": "KGS", "continent": "Asia", "continent_code": "AS", "alpha_3": "KGZ" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Lao People's Democratic Republic", "code": "LA", "id": 123, "phone": 856, "symbol": "₭", "capital": "Vientiane", "currency": "LAK", "continent": "Asia", "continent_code": "AS", "alpha_3": "LAO" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Latvia", "code": "LV", "id": 124, "phone": 371, "symbol": "€", "capital": "Riga", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "LVA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Lebanon", "code": "LB", "id": 125, "phone": 961, "symbol": "£", "capital": "Beirut", "currency": "LBP", "continent": "Asia", "continent_code": "AS", "alpha_3": "LBN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Lesotho", "code": "LS", "id": 126, "phone": 266, "symbol": "L", "capital": "Maseru", "currency": "LSL", "continent": "Africa", "continent_code": "AF", "alpha_3": "LSO" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Liberia", "code": "LR", "id": 127, "phone": 231, "symbol": "$", "capital": "Monrovia", "currency": "LRD", "continent": "Africa", "continent_code": "AF", "alpha_3": "LBR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Libyan Arab Jamahiriya", "code": "LY", "id": 128, "phone": 218, "symbol": "د.ل", "capital": "Tripolis", "currency": "LYD", "continent": "Africa", "continent_code": "AF", "alpha_3": "LBY" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Liechtenstein", "code": "LI", "id": 129, "phone": 423, "symbol": "CHf", "capital": "Vaduz", "currency": "CHF", "continent": "Europe", "continent_code": "EU", "alpha_3": "LIE" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Lithuania", "code": "LT", "id": 130, "phone": 370, "symbol": "€", "capital": "Vilnius", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "LTU" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Luxembourg", "code": "LU", "id": 131, "phone": 352, "symbol": "€", "capital": "Luxembourg", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "LUX" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Macao", "code": "MO", "id": 132, "phone": 853, "symbol": "$", "capital": "Macao", "currency": "MOP", "continent": "Asia", "continent_code": "AS", "alpha_3": "MAC" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Macedonia, the Former Yugoslav Republic of", "code": "MK", "id": 133, "phone": 389, "symbol": "ден", "capital": "Skopje", "currency": "MKD", "continent": "Europe", "continent_code": "EU", "alpha_3": "MKD" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Madagascar", "code": "MG", "id": 134, "phone": 261, "symbol": "Ar", "capital": "Antananarivo", "currency": "MGA", "continent": "Africa", "continent_code": "AF", "alpha_3": "MDG" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Malawi", "code": "MW", "id": 135, "phone": 265, "symbol": "MK", "capital": "Lilongwe", "currency": "MWK", "continent": "Africa", "continent_code": "AF", "alpha_3": "MWI" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Malaysia", "code": "MY", "id": 136, "phone": 60, "symbol": "RM", "capital": "Kuala Lumpur", "currency": "MYR", "continent": "Asia", "continent_code": "AS", "alpha_3": "MYS" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Maldives", "code": "MV", "id": 137, "phone": 960, "symbol": "Rf", "capital": "Male", "currency": "MVR", "continent": "Asia", "continent_code": "AS", "alpha_3": "MDV" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Mali", "code": "ML", "id": 138, "phone": 223, "symbol": "CFA", "capital": "Bamako", "currency": "XOF", "continent": "Africa", "continent_code": "AF", "alpha_3": "MLI" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Malta", "code": "MT", "id": 139, "phone": 356, "symbol": "€", "capital": "Valletta", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "MLT" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Marshall Islands", "code": "MH", "id": 140, "phone": 692, "symbol": "$", "capital": "Majuro", "currency": "USD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "MHL" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Martinique", "code": "MQ", "id": 141, "phone": 596, "symbol": "€", "capital": "Fort-de-France", "currency": "EUR", "continent": "North America", "continent_code": "NA", "alpha_3": "MTQ" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Mauritania", "code": "MR", "id": 142, "phone": 222, "symbol": "MRU", "capital": "Nouakchott", "currency": "MRO", "continent": "Africa", "continent_code": "AF", "alpha_3": "MRT" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Mauritius", "code": "MU", "id": 143, "phone": 230, "symbol": "₨", "capital": "Port Louis", "currency": "MUR", "continent": "Africa", "continent_code": "AF", "alpha_3": "MUS" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Mayotte", "code": "YT", "id": 144, "phone": 269, "symbol": "€", "capital": "Mamoudzou", "currency": "EUR", "continent": "Africa", "continent_code": "AF", "alpha_3": "MYT" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Mexico", "code": "MX", "id": 145, "phone": 52, "symbol": "$", "capital": "Mexico City", "currency": "MXN", "continent": "North America", "continent_code": "NA", "alpha_3": "MEX" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Micronesia, Federated States of", "code": "FM", "id": 146, "phone": 691, "symbol": "$", "capital": "Palikir", "currency": "USD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "FSM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Moldova, Republic of", "code": "MD", "id": 147, "phone": 373, "symbol": "L", "capital": "Chisinau", "currency": "MDL", "continent": "Europe", "continent_code": "EU", "alpha_3": "MDA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Monaco", "code": "MC", "id": 148, "phone": 377, "symbol": "€", "capital": "Monaco", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "MCO" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Mongolia", "code": "MN", "id": 149, "phone": 976, "symbol": "₮", "capital": "Ulan Bator", "currency": "MNT", "continent": "Asia", "continent_code": "AS", "alpha_3": "MNG" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Montenegro", "code": "ME", "id": 150, "phone": 382, "symbol": "€", "capital": "Podgorica", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "MNE" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Montserrat", "code": "MS", "id": 151, "phone": 1664, "symbol": "$", "capital": "Plymouth", "currency": "XCD", "continent": "North America", "continent_code": "NA", "alpha_3": "MSR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Morocco", "code": "MA", "id": 152, "phone": 212, "symbol": "DH", "capital": "Rabat", "currency": "MAD", "continent": "Africa", "continent_code": "AF", "alpha_3": "MAR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Mozambique", "code": "MZ", "id": 153, "phone": 258, "symbol": "MT", "capital": "Maputo", "currency": "MZN", "continent": "Africa", "continent_code": "AF", "alpha_3": "MOZ" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Myanmar", "code": "MM", "id": 154, "phone": 95, "symbol": "K", "capital": "Nay Pyi Taw", "currency": "MMK", "continent": "Asia", "continent_code": "AS", "alpha_3": "MMR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Namibia", "code": "NA", "id": 155, "phone": 264, "symbol": "$", "capital": "Windhoek", "currency": "NAD", "continent": "Africa", "continent_code": "AF", "alpha_3": "NAM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Nauru", "code": "NR", "id": 156, "phone": 674, "symbol": "$", "capital": "Yaren", "currency": "AUD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "NRU" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Nepal", "code": "NP", "id": 157, "phone": 977, "symbol": "₨", "capital": "Kathmandu", "currency": "NPR", "continent": "Asia", "continent_code": "AS", "alpha_3": "NPL" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Netherlands", "code": "NL", "id": 158, "phone": 31, "symbol": "€", "capital": "Amsterdam", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "NLD" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Netherlands Antilles", "code": "AN", "id": 159, "phone": 599, "symbol": "NAf", "capital": "Willemstad", "currency": "ANG", "continent": "North America", "continent_code": "NA", "alpha_3": "ANT" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "New Caledonia", "code": "NC", "id": 160, "phone": 687, "symbol": "₣", "capital": "Noumea", "currency": "XPF", "continent": "Oceania", "continent_code": "OC", "alpha_3": "NCL" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "New Zealand", "code": "NZ", "id": 161, "phone": 64, "symbol": "$", "capital": "Wellington", "currency": "NZD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "NZL" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Nicaragua", "code": "NI", "id": 162, "phone": 505, "symbol": "C$", "capital": "Managua", "currency": "NIO", "continent": "North America", "continent_code": "NA", "alpha_3": "NIC" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Niger", "code": "NE", "id": 163, "phone": 227, "symbol": "CFA", "capital": "Niamey", "currency": "XOF", "continent": "Africa", "continent_code": "AF", "alpha_3": "NER" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Nigeria", "code": "NG", "id": 164, "phone": 234, "symbol": "₦", "capital": "Abuja", "currency": "NGN", "continent": "Africa", "continent_code": "AF", "alpha_3": "NGA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Niue", "code": "NU", "id": 165, "phone": 683, "symbol": "$", "capital": "Alofi", "currency": "NZD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "NIU" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Norfolk Island", "code": "NF", "id": 166, "phone": 672, "symbol": "$", "capital": "Kingston", "currency": "AUD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "NFK" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Northern Mariana Islands", "code": "MP", "id": 167, "phone": 1670, "symbol": "$", "capital": "Saipan", "currency": "USD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "MNP" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Norway", "code": "NO", "id": 168, "phone": 47, "symbol": "kr", "capital": "Oslo", "currency": "NOK", "continent": "Europe", "continent_code": "EU", "alpha_3": "NOR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Oman", "code": "OM", "id": 169, "phone": 968, "symbol": ".ع.ر", "capital": "Muscat", "currency": "OMR", "continent": "Asia", "continent_code": "AS", "alpha_3": "OMN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Pakistan", "code": "PK", "id": 170, "phone": 92, "symbol": "₨", "capital": "Islamabad", "currency": "PKR", "continent": "Asia", "continent_code": "AS", "alpha_3": "PAK" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Palau", "code": "PW", "id": 171, "phone": 680, "symbol": "$", "capital": "Melekeok", "currency": "USD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "PLW" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Palestinian Territory, Occupied", "code": "PS", "id": 172, "phone": 970, "symbol": "₪", "capital": "East Jerusalem", "currency": "ILS", "continent": "Asia", "continent_code": "AS", "alpha_3": "PSE" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Panama", "code": "PA", "id": 173, "phone": 507, "symbol": "B/.", "capital": "Panama City", "currency": "PAB", "continent": "North America", "continent_code": "NA", "alpha_3": "PAN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Papua New Guinea", "code": "PG", "id": 174, "phone": 675, "symbol": "K", "capital": "Port Moresby", "currency": "PGK", "continent": "Oceania", "continent_code": "OC", "alpha_3": "PNG" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Paraguay", "code": "PY", "id": 175, "phone": 595, "symbol": "₲", "capital": "Asuncion", "currency": "PYG", "continent": "South America", "continent_code": "SA", "alpha_3": "PRY" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Peru", "code": "PE", "id": 176, "phone": 51, "symbol": "S/.", "capital": "Lima", "currency": "PEN", "continent": "South America", "continent_code": "SA", "alpha_3": "PER" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Philippines", "code": "PH", "id": 177, "phone": 63, "symbol": "₱", "capital": "Manila", "currency": "PHP", "continent": "Asia", "continent_code": "AS", "alpha_3": "PHL" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Pitcairn", "code": "PN", "id": 178, "phone": 64, "symbol": "$", "capital": "Adamstown", "currency": "NZD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "PCN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Poland", "code": "PL", "id": 179, "phone": 48, "symbol": "zł", "capital": "Warsaw", "currency": "PLN", "continent": "Europe", "continent_code": "EU", "alpha_3": "POL" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Portugal", "code": "PT", "id": 180, "phone": 351, "symbol": "€", "capital": "Lisbon", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "PRT" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Puerto Rico", "code": "PR", "id": 181, "phone": 1787, "symbol": "$", "capital": "San Juan", "currency": "USD", "continent": "North America", "continent_code": "NA", "alpha_3": "PRI" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Qatar", "code": "QA", "id": 182, "phone": 974, "symbol": "ق.ر", "capital": "Doha", "currency": "QAR", "continent": "Asia", "continent_code": "AS", "alpha_3": "QAT" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Reunion", "code": "RE", "id": 183, "phone": 262, "symbol": "€", "capital": "Saint-Denis", "currency": "EUR", "continent": "Africa", "continent_code": "AF", "alpha_3": "REU" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Romania", "code": "RO", "id": 184, "phone": 40, "symbol": "lei", "capital": "Bucharest", "currency": "RON", "continent": "Europe", "continent_code": "EU", "alpha_3": "ROM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Russian Federation", "code": "RU", "id": 185, "phone": 70, "symbol": "₽", "capital": "Moscow", "currency": "RUB", "continent": "Asia", "continent_code": "AS", "alpha_3": "RUS" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Rwanda", "code": "RW", "id": 186, "phone": 250, "symbol": "FRw", "capital": "Kigali", "currency": "RWF", "continent": "Africa", "continent_code": "AF", "alpha_3": "RWA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Saint Barthelemy", "code": "BL", "id": 187, "phone": 590, "symbol": "€", "capital": "Gustavia", "currency": "EUR", "continent": "North America", "continent_code": "NA", "alpha_3": "BLM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Saint Helena", "code": "SH", "id": 188, "phone": 290, "symbol": "£", "capital": "Jamestown", "currency": "SHP", "continent": "Africa", "continent_code": "AF", "alpha_3": "SHN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Saint Kitts and Nevis", "code": "KN", "id": 189, "phone": 1869, "symbol": "$", "capital": "Basseterre", "currency": "XCD", "continent": "North America", "continent_code": "NA", "alpha_3": "KNA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Saint Lucia", "code": "LC", "id": 190, "phone": 1758, "symbol": "$", "capital": "Castries", "currency": "XCD", "continent": "North America", "continent_code": "NA", "alpha_3": "LCA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Saint Martin", "code": "MF", "id": 191, "phone": 590, "symbol": "€", "capital": "Marigot", "currency": "EUR", "continent": "North America", "continent_code": "NA", "alpha_3": "MAF" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Saint Pierre and Miquelon", "code": "PM", "id": 192, "phone": 508, "symbol": "€", "capital": "Saint-Pierre", "currency": "EUR", "continent": "North America", "continent_code": "NA", "alpha_3": "SPM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Saint Vincent and the Grenadines", "code": "VC", "id": 193, "phone": 1784, "symbol": "$", "capital": "Kingstown", "currency": "XCD", "continent": "North America", "continent_code": "NA", "alpha_3": "VCT" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Samoa", "code": "WS", "id": 194, "phone": 684, "symbol": "SAT", "capital": "Apia", "currency": "WST", "continent": "Oceania", "continent_code": "OC", "alpha_3": "WSM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "San Marino", "code": "SM", "id": 195, "phone": 378, "symbol": "€", "capital": "San Marino", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "SMR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Sao Tome and Principe", "code": "ST", "id": 196, "phone": 239, "symbol": "Db", "capital": "Sao Tome", "currency": "STD", "continent": "Africa", "continent_code": "AF", "alpha_3": "STP" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Saudi Arabia", "code": "SA", "id": 197, "phone": 966, "symbol": "﷼", "capital": "Riyadh", "currency": "SAR", "continent": "Asia", "continent_code": "AS", "alpha_3": "SAU" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Senegal", "code": "SN", "id": 198, "phone": 221, "symbol": "CFA", "capital": "Dakar", "currency": "XOF", "continent": "Africa", "continent_code": "AF", "alpha_3": "SEN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Serbia", "code": "RS", "id": 199, "phone": 381, "symbol": "din", "capital": "Belgrade", "currency": "RSD", "continent": "Europe", "continent_code": "EU", "alpha_3": "SRB" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Serbia and Montenegro", "code": "CS", "id": 200, "phone": 381, "symbol": "din", "capital": "Belgrade", "currency": "RSD", "continent": "Europe", "continent_code": "EU", "alpha_3": "SCG" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Seychelles", "code": "SC", "id": 201, "phone": 248, "symbol": "SRe", "capital": "Victoria", "currency": "SCR", "continent": "Africa", "continent_code": "AF", "alpha_3": "SYC" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Sierra Leone", "code": "SL", "id": 202, "phone": 232, "symbol": "Le", "capital": "Freetown", "currency": "SLL", "continent": "Africa", "continent_code": "AF", "alpha_3": "SLE" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Singapore", "code": "SG", "id": 203, "phone": 65, "symbol": "$", "capital": "Singapur", "currency": "SGD", "continent": "Asia", "continent_code": "AS", "alpha_3": "SGP" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Sint Maarten", "code": "SX", "id": 204, "phone": 1, "symbol": "ƒ", "capital": "Philipsburg", "currency": "ANG", "continent": "North America", "continent_code": "NA", "alpha_3": "SXM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Slovakia", "code": "SK", "id": 205, "phone": 421, "symbol": "€", "capital": "Bratislava", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "SVK" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Slovenia", "code": "SI", "id": 206, "phone": 386, "symbol": "€", "capital": "Ljubljana", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "SVN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Solomon Islands", "code": "SB", "id": 207, "phone": 677, "symbol": "Si$", "capital": "Honiara", "currency": "SBD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "SLB" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Somalia", "code": "SO", "id": 208, "phone": 252, "symbol": "Sh.so.", "capital": "Mogadishu", "currency": "SOS", "continent": "Africa", "continent_code": "AF", "alpha_3": "SOM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "South Africa", "code": "ZA", "id": 209, "phone": 27, "symbol": "R", "capital": "Pretoria", "currency": "ZAR", "continent": "Africa", "continent_code": "AF", "alpha_3": "ZAF" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "South Georgia and the South Sandwich Islands", "code": "GS", "id": 210, "phone": 500, "symbol": "£", "capital": "Grytviken", "currency": "GBP", "continent": "Antarctica", "continent_code": "AN", "alpha_3": "SGS" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "South Sudan", "code": "SS", "id": 211, "phone": 211, "symbol": "£", "capital": "Juba", "currency": "SSP", "continent": "Africa", "continent_code": "AF", "alpha_3": "SSD" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Spain", "code": "ES", "id": 212, "phone": 34, "symbol": "€", "capital": "Madrid", "currency": "EUR", "continent": "Europe", "continent_code": "EU", "alpha_3": "ESP" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Sri Lanka", "code": "LK", "id": 213, "phone": 94, "symbol": "Rs", "capital": "Colombo", "currency": "LKR", "continent": "Asia", "continent_code": "AS", "alpha_3": "LKA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Sudan", "code": "SD", "id": 214, "phone": 249, "symbol": ".س.ج", "capital": "Khartoum", "currency": "SDG", "continent": "Africa", "continent_code": "AF", "alpha_3": "SDN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Suriname", "code": "SR", "id": 215, "phone": 597, "symbol": "$", "capital": "Paramaribo", "currency": "SRD", "continent": "South America", "continent_code": "SA", "alpha_3": "SUR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Svalbard and Jan Mayen", "code": "SJ", "id": 216, "phone": 47, "symbol": "kr", "capital": "Longyearbyen", "currency": "NOK", "continent": "Europe", "continent_code": "EU", "alpha_3": "SJM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Swaziland", "code": "SZ", "id": 217, "phone": 268, "symbol": "E", "capital": "Mbabane", "currency": "SZL", "continent": "Africa", "continent_code": "AF", "alpha_3": "SWZ" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Sweden", "code": "SE", "id": 218, "phone": 46, "symbol": "kr", "capital": "Stockholm", "currency": "SEK", "continent": "Europe", "continent_code": "EU", "alpha_3": "SWE" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Switzerland", "code": "CH", "id": 219, "phone": 41, "symbol": "CHf", "capital": "Berne", "currency": "CHF", "continent": "Europe", "continent_code": "EU", "alpha_3": "CHE" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Syrian Arab Republic", "code": "SY", "id": 220, "phone": 963, "symbol": "LS", "capital": "Damascus", "currency": "SYP", "continent": "Asia", "continent_code": "AS", "alpha_3": "SYR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Taiwan, Province of China", "code": "TW", "id": 221, "phone": 886, "symbol": "$", "capital": "Taipei", "currency": "TWD", "continent": "Asia", "continent_code": "AS", "alpha_3": "TWN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Tajikistan", "code": "TJ", "id": 222, "phone": 992, "symbol": "SM", "capital": "Dushanbe", "currency": "TJS", "continent": "Asia", "continent_code": "AS", "alpha_3": "TJK" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Tanzania, United Republic of", "code": "TZ", "id": 223, "phone": 255, "symbol": "TSh", "capital": "Dodoma", "currency": "TZS", "continent": "Africa", "continent_code": "AF", "alpha_3": "TZA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Thailand", "code": "TH", "id": 224, "phone": 66, "symbol": "฿", "capital": "Bangkok", "currency": "THB", "continent": "Asia", "continent_code": "AS", "alpha_3": "THA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Timor-Leste", "code": "TL", "id": 225, "phone": 670, "symbol": "$", "capital": "Dili", "currency": "USD", "continent": "Asia", "continent_code": "AS", "alpha_3": "TLS" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Togo", "code": "TG", "id": 226, "phone": 228, "symbol": "CFA", "capital": "Lome", "currency": "XOF", "continent": "Africa", "continent_code": "AF", "alpha_3": "TGO" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Tokelau", "code": "TK", "id": 227, "phone": 690, "symbol": "$", "capital": "", "currency": "NZD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "TKL" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Tonga", "code": "TO", "id": 228, "phone": 676, "symbol": "$", "capital": "Nuku'alofa", "currency": "TOP", "continent": "Oceania", "continent_code": "OC", "alpha_3": "TON" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Trinidad and Tobago", "code": "TT", "id": 229, "phone": 1868, "symbol": "$", "capital": "Port of Spain", "currency": "TTD", "continent": "North America", "continent_code": "NA", "alpha_3": "TTO" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Tunisia", "code": "TN", "id": 230, "phone": 216, "symbol": "ت.د", "capital": "Tunis", "currency": "TND", "continent": "Africa", "continent_code": "AF", "alpha_3": "TUN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Turkey", "code": "TR", "id": 231, "phone": 90, "symbol": "₺", "capital": "Ankara", "currency": "TRY", "continent": "Asia", "continent_code": "AS", "alpha_3": "TUR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Turkmenistan", "code": "TM", "id": 232, "phone": 7370, "symbol": "T", "capital": "Ashgabat", "currency": "TMT", "continent": "Asia", "continent_code": "AS", "alpha_3": "TKM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Turks and Caicos Islands", "code": "TC", "id": 233, "phone": 1649, "symbol": "$", "capital": "Cockburn Town", "currency": "USD", "continent": "North America", "continent_code": "NA", "alpha_3": "TCA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Tuvalu", "code": "TV", "id": 234, "phone": 688, "symbol": "$", "capital": "Funafuti", "currency": "AUD", "continent": "Oceania", "continent_code": "OC", "alpha_3": "TUV" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Uganda", "code": "UG", "id": 235, "phone": 256, "symbol": "USh", "capital": "Kampala", "currency": "UGX", "continent": "Africa", "continent_code": "AF", "alpha_3": "UGA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Ukraine", "code": "UA", "id": 236, "phone": 380, "symbol": "₴", "capital": "Kiev", "currency": "UAH", "continent": "Europe", "continent_code": "EU", "alpha_3": "UKR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "United Arab Emirates", "code": "AE", "id": 237, "phone": 971, "symbol": "إ.د", "capital": "Abu Dhabi", "currency": "AED", "continent": "Asia", "continent_code": "AS", "alpha_3": "ARE" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "United Kingdom", "code": "GB", "id": 238, "phone": 44, "symbol": "£", "capital": "London", "currency": "GBP", "continent": "Europe", "continent_code": "EU", "alpha_3": "GBR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "United States", "code": "US", "id": 239, "phone": 1, "symbol": "$", "capital": "Washington", "currency": "USD", "continent": "North America", "continent_code": "NA", "alpha_3": "USA" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "United States Minor Outlying Islands", "code": "UM", "id": 240, "phone": 1, "symbol": "$", "capital": "", "currency": "USD", "continent": "North America", "continent_code": "NA", "alpha_3": "UMI" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Uruguay", "code": "UY", "id": 241, "phone": 598, "symbol": "$", "capital": "Montevideo", "currency": "UYU", "continent": "South America", "continent_code": "SA", "alpha_3": "URY" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Uzbekistan", "code": "UZ", "id": 242, "phone": 998, "symbol": "лв", "capital": "Tashkent", "currency": "UZS", "continent": "Asia", "continent_code": "AS", "alpha_3": "UZB" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Vanuatu", "code": "VU", "id": 243, "phone": 678, "symbol": "VT", "capital": "Port Vila", "currency": "VUV", "continent": "Oceania", "continent_code": "OC", "alpha_3": "VUT" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Venezuela", "code": "VE", "id": 244, "phone": 58, "symbol": "Bs", "capital": "Caracas", "currency": "VEF", "continent": "South America", "continent_code": "SA", "alpha_3": "VEN" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Viet Nam", "code": "VN", "id": 245, "phone": 84, "symbol": "₫", "capital": "Hanoi", "currency": "VND", "continent": "Asia", "continent_code": "AS", "alpha_3": "VNM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Virgin Islands, British", "code": "VG", "id": 246, "phone": 1284, "symbol": "$", "capital": "Road Town", "currency": "USD", "continent": "North America", "continent_code": "NA", "alpha_3": "VGB" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Virgin Islands, U.s.", "code": "VI", "id": 247, "phone": 1340, "symbol": "$", "capital": "Charlotte Amalie", "currency": "USD", "continent": "North America", "continent_code": "NA", "alpha_3": "VIR" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Wallis and Futuna", "code": "WF", "id": 248, "phone": 681, "symbol": "₣", "capital": "Mata Utu", "currency": "XPF", "continent": "Oceania", "continent_code": "OC", "alpha_3": "WLF" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Western Sahara", "code": "EH", "id": 249, "phone": 212, "symbol": "MAD", "capital": "El-Aaiun", "currency": "MAD", "continent": "Africa", "continent_code": "AF", "alpha_3": "ESH" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Yemen", "code": "YE", "id": 250, "phone": 967, "symbol": "﷼", "capital": "Sanaa", "currency": "YER", "continent": "Asia", "continent_code": "AS", "alpha_3": "YEM" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Zambia", "code": "ZM", "id": 251, "phone": 260, "symbol": "ZK", "capital": "Lusaka", "currency": "ZMW", "continent": "Africa", "continent_code": "AF", "alpha_3": "ZMB" },
    { "address": "https://en.wikipedia.org/wiki/Wikipedia", "name": "Zimbabwe", "code": "ZW", "id": 252, "phone": 263, "symbol": "$", "capital": "Harare", "currency": "ZWL", "continent": "Africa", "continent_code": "AF", "alpha_3": "ZWE" }
];

var flags = [
    'url(./flags/1.jpg)',
    'url(./flags/2.jpg)',
    'url(./flags/3.jpg)',
    'url(./flags/4.jpg)',
    'url(./flags/5.jpg)',
    'url(./flags/6.jpg)',
    'url(./flags/7.jpg)',
    'url(./flags/8.jpg)',
    'url(./flags/9.jpg)',
    'url(./flags/10.jpg)',
    'url(./flags/11.jpg)',
    'url(./flags/12.jpg)',
    'url(./flags/13.jpg)',
    'url(./flags/14.jpg)',
    'url(./flags/15.jpg)',
    'url(./flags/16.jpg)',
    'url(./flags/17.jpg)',
    'url(./flags/18.jpg)',
    'url(./flags/19.jpg)',
    'url(./flags/20.jpg)',
    'url(./flags/21.jpg)',
    'url(./flags/22.jpg)',
    'url(./flags/23.jpg)',
    'url(./flags/24.jpg)',
    'url(./flags/25.jpg)',
    'url(./flags/26.jpg)',
    'url(./flags/27.jpg)',
    'url(./flags/28.jpg)',
    'url(./flags/29.jpg)',
    'url(./flags/30.jpg)',
    'url(./flags/31.jpg)',
    'url(./flags/32.jpg)',
    'url(./flags/33.jpg)',
    'url(./flags/34.jpg)',
    'url(./flags/35.jpg)',
    'url(./flags/36.jpg)',
    'url(./flags/37.jpg)',
    'url(./flags/38.jpg)',
    'url(./flags/39.jpg)',
    'url(./flags/40.jpg)',
    'url(./flags/41.jpg)',
    'url(./flags/42.jpg)',
    'url(./flags/43.jpg)',
    'url(./flags/44.jpg)',
    'url(./flags/45.jpg)',
    'url(./flags/46.jpg)',
    'url(./flags/47.jpg)',
    'url(./flags/48.jpg)',
    'url(./flags/49.jpg)',
    'url(./flags/50.jpg)',
    'url(./flags/51.jpg)',
    'url(./flags/52.jpg)',
    'url(./flags/53.jpg)',
    'url(./flags/54.jpg)',
    'url(./flags/55.jpg)',
    'url(./flags/56.jpg)',
    'url(./flags/57.jpg)',
    'url(./flags/58.jpg)',
    'url(./flags/59.jpg)',
    'url(./flags/60.jpg)',
    'url(./flags/61.jpg)',
    'url(./flags/62.jpg)',
    'url(./flags/63.jpg)',
    'url(./flags/64.jpg)',
    'url(./flags/65.jpg)',
    'url(./flags/66.jpg)',
    'url(./flags/67.jpg)',
    'url(./flags/68.jpg)',
    'url(./flags/69.jpg)',
    'url(./flags/70.jpg)',
    'url(./flags/71.jpg)',
    'url(./flags/72.jpg)',
    'url(./flags/73.jpg)',
    'url(./flags/74.jpg)',
    'url(./flags/75.jpg)',
    'url(./flags/76.jpg)',
    'url(./flags/77.jpg)',
    'url(./flags/78.jpg)',
    'url(./flags/79.jpg)',
    'url(./flags/80.jpg)',
    'url(./flags/81.jpg)',
    'url(./flags/82.jpg)',
    'url(./flags/83.jpg)',
    'url(./flags/84.jpg)',
    'url(./flags/85.jpg)',
    'url(./flags/86.jpg)',
    'url(./flags/87.jpg)',
    'url(./flags/88.jpg)',
    'url(./flags/89.jpg)',
    'url(./flags/90.jpg)',
    'url(./flags/91.jpg)',
    'url(./flags/92.jpg)',
    'url(./flags/93.jpg)',
    'url(./flags/94.jpg)',
    'url(./flags/95.jpg)',
    'url(./flags/96.jpg)',
    'url(./flags/97.jpg)',
    'url(./flags/98.jpg)',
    'url(./flags/99.jpg)',
    'url(./flags/100.jpg)',
    'url(./flags/101.jpg)',
    'url(./flags/102.jpg)',
    'url(./flags/103.jpg)',
    'url(./flags/104.jpg)',
    'url(./flags/105.jpg)',
    'url(./flags/106.jpg)',
    'url(./flags/107.jpg)',
    'url(./flags/108.jpg)',
    'url(./flags/109.jpg)',
    'url(./flags/110.jpg)',
    'url(./flags/111.jpg)',
    'url(./flags/112.jpg)',
    'url(./flags/113.jpg)',
    'url(./flags/114.jpg)',
    'url(./flags/115.jpg)',
    'url(./flags/116.jpg)',
    'url(./flags/117.jpg)',
    'url(./flags/118.jpg)',
    'url(./flags/119.jpg)',
    'url(./flags/120.jpg)',
    'url(./flags/121.jpg)',
    'url(./flags/122.jpg)',
    'url(./flags/123.jpg)',
    'url(./flags/124.jpg)',
    'url(./flags/125.jpg)',
    'url(./flags/126.jpg)',
    'url(./flags/127.jpg)',
    'url(./flags/128.jpg)',
    'url(./flags/129.jpg)',
    'url(./flags/130.jpg)',
    'url(./flags/131.jpg)',
    'url(./flags/132.jpg)',
    'url(./flags/133.jpg)',
    'url(./flags/134.jpg)',
    'url(./flags/135.jpg)',
    'url(./flags/136.jpg)',
    'url(./flags/137.jpg)',
    'url(./flags/138.jpg)',
    'url(./flags/139.jpg)',
    'url(./flags/140.jpg)',
    'url(./flags/141.jpg)',
    'url(./flags/142.jpg)',
    'url(./flags/143.jpg)',
    'url(./flags/144.jpg)',
    'url(./flags/145.jpg)',
    'url(./flags/146.jpg)',
    'url(./flags/147.jpg)',
    'url(./flags/148.jpg)',
    'url(./flags/149.jpg)',
    'url(./flags/150.jpg)',
    'url(./flags/151.jpg)',
    'url(./flags/152.jpg)',
    'url(./flags/153.jpg)',
    'url(./flags/154.jpg)',
    'url(./flags/155.jpg)',
    'url(./flags/156.jpg)',
    'url(./flags/157.jpg)',
    'url(./flags/158.jpg)',
    'url(./flags/159.jpg)',
    'url(./flags/160.jpg)',
    'url(./flags/161.jpg)',
    'url(./flags/162.jpg)',
    'url(./flags/163.jpg)',
    'url(./flags/164.jpg)',
    'url(./flags/165.jpg)',
    'url(./flags/166.jpg)',
    'url(./flags/167.jpg)',
    'url(./flags/168.jpg)',
    'url(./flags/169.jpg)',
    'url(./flags/170.jpg)',
    'url(./flags/171.jpg)',
    'url(./flags/172.jpg)',
    'url(./flags/173.jpg)',
    'url(./flags/174.jpg)',
    'url(./flags/175.jpg)',
    'url(./flags/176.jpg)',
    'url(./flags/177.jpg)',
    'url(./flags/178.jpg)',
    'url(./flags/179.jpg)',
    'url(./flags/180.jpg)',
    'url(./flags/181.jpg)',
    'url(./flags/182.jpg)',
    'url(./flags/183.jpg)',
    'url(./flags/184.jpg)',
    'url(./flags/185.jpg)',
    'url(./flags/186.jpg)',
    'url(./flags/187.jpg)',
    'url(./flags/188.jpg)',
    'url(./flags/189.jpg)',
    'url(./flags/190.jpg)',
    'url(./flags/191.jpg)',
    'url(./flags/192.jpg)',
    'url(./flags/193.jpg)',
    'url(./flags/194.jpg)',
    'url(./flags/195.jpg)',
    'url(./flags/196.jpg)',
    'url(./flags/197.jpg)',
    'url(./flags/198.jpg)',
    'url(./flags/199.jpg)',
    'url(./flags/200.jpg)',
    'url(./flags/201.jpg)',
    'url(./flags/202.jpg)',
    'url(./flags/203.jpg)',
    'url(./flags/204.jpg)',
    'url(./flags/205.jpg)',
    'url(./flags/206.jpg)',
    'url(./flags/207.jpg)',
    'url(./flags/208.jpg)',
    'url(./flags/209.jpg)',
    'url(./flags/210.jpg)',
    'url(./flags/211.jpg)',
    'url(./flags/212.jpg)',
    'url(./flags/213.jpg)',
    'url(./flags/214.jpg)',
    'url(./flags/215.jpg)',
    'url(./flags/216.jpg)',
    'url(./flags/217.jpg)',
    'url(./flags/218.jpg)',
    'url(./flags/219.jpg)',
    'url(./flags/220.jpg)',
    'url(./flags/221.jpg)',
    'url(./flags/222.jpg)',
    'url(./flags/223.jpg)',
    'url(./flags/224.jpg)',
    'url(./flags/225.jpg)',
    'url(./flags/226.jpg)',
    'url(./flags/227.jpg)',
    'url(./flags/228.jpg)',
    'url(./flags/229.jpg)',
    'url(./flags/230.jpg)',
    'url(./flags/231.jpg)',
    'url(./flags/232.jpg)',
    'url(./flags/233.jpg)',
    'url(./flags/234.jpg)',
    'url(./flags/235.jpg)',
    'url(./flags/236.jpg)',
    'url(./flags/237.jpg)',
    'url(./flags/238.jpg)',
    'url(./flags/239.jpg)',
    'url(./flags/240.jpg)',
    'url(./flags/241.jpg)',
    'url(./flags/242.jpg)',
    'url(./flags/243.jpg)',
    'url(./flags/244.jpg)',
    'url(./flags/245.jpg)',
    'url(./flags/246.jpg)',
    'url(./flags/247.jpg)',
    'url(./flags/248.jpg)',
    'url(./flags/249.jpg)',
    'url(./flags/250.jpg)',
    'url(./flags/251.jpg)',
    'url(./flags/252.jpg)',
]

let optionList = document.getElementById('continent_select').options;
countries.forEach(option =>
    optionList.add(
        new Option(option.name)
    )
);

document.querySelector('#findButton').addEventListener('click', findContinent);
function findContinent() {
    let val = document.getElementById('continent_select').value;
    if (val == "") {
        alert('Please select the country first.')
    } else {
        document.getElementById('countryLink').innerHTML = "more details about " + val;
        countries.forEach(function (ele) {
            if (ele.name == val) {
                let n = +(ele.id)
                document.getElementById("countryLink").href = ele.address
                document.getElementById('background').style.backgroundImage = flags[n - 1]
                document.getElementById('countryName').innerText = ele.name
                document.getElementById('countryCode').innerText = ele.code
                document.getElementById('countryId').innerText = ele.id
                document.getElementById('phoneCode').innerText = ele.phone
                document.getElementById('capitalName').innerText = ele.capital
                document.getElementById('currency').innerText = ele.currency
                document.getElementById('symbol').innerText = ele.symbol
                document.getElementById('continentName').innerText = ele.continent
                document.getElementById('continentCode').innerText = ele.continent_code
                document.getElementById('alpha3').innerText = ele.alpha_3
            }
        })
    }
}

function fun() {
    location.reload();
}